Repository 22-winter-SV-bootcamp/backend, pull requests merged in 2023-01, with the labels that each got.

#35 feature/#32 : task 없을때 예외처리
  backend/images/views.py
Labels: 기능구현

#36 Feature/#33 : swagger api 테스트 기능
  backend/images/views.py
  backend/styles/views.py
  backend/swagger/swagger.py
Labels: 기능구현

#42 Refactor/#41 task result 반환 api 리팩토링
  backend/backend/settings.py
  backend/images/urls.py
  backend/images/views.py
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 리팩토링

#48 Feature/#47 캐싱으로 랭킹 반환
  backend/images/tasks.py
  backend/images/views.py
  backend/styles/ranking.py
  backend/styles/serializers.py
  backend/styles/views.py
  docker-compose.yml
  monitoring/alertmanager/config.yml
  monitoring/grafana/grafana.ini
Labels: 기능구현

#49 Feature/#46 cors setting
  ai/ai/settings.py
  ai/requirements.txt
  backend/backend/settings.py
  docker-compose.prod.yml
Labels: 환경설정

#57 Feature/#56 styles 리팩토링
  backend/backend/urls.py
  backend/styles/ranking.py
  backend/styles/views.py
Labels: 리팩토링

#58 Feature/#51 images 리팩토링
  ai/images/views.py
  backend/images/result.py
  backend/images/tasks.py
  backend/images/urls.py
  backend/images/utils.py
  backend/images/views.py
Labels: 리팩토링
